name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install backend
        run: npm install
      - name: npm install frontend
        run: npm install --prefix client
      - name: lint backend
        run: npm run lint
      - name: lint frontend
        run: npm run lint --prefix client
      - name: test 
        run: npm run test
