name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install frontend
        run: npm install --prefix client
      - name: lint frontend
        run: npm run lint --prefix client
      - name: test frontend
        run: CI=true npm test --prefix client
      - name: npm install backend
        run: npm install
      - name: lint backend
        run: npm run lint
# https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions
      - name: prepare backend for tests
        run: |
            cat << EOF > .env
            MONGODB_URI_TEST=${{ secrets.MONGODB_URI_TEST }}
            PORT=3000
            SECRET=${{ secrets.SECRET }}
            EOF
      - name: test backend
        run: npm run test
